//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYSEPro.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.clientAPISoap")]
    public interface clientAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/usersDT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string usersDT(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/usersDT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> usersDTAsync(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsersDateSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UsersDateSearch(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsersDateSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UsersDateSearchAsync(System.DateTime startDate, System.DateTime endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface clientAPISoapChannel : NYSEPro.ServiceReference1.clientAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class clientAPISoapClient : System.ServiceModel.ClientBase<NYSEPro.ServiceReference1.clientAPISoap>, NYSEPro.ServiceReference1.clientAPISoap {
        
        public clientAPISoapClient() {
        }
        
        public clientAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public clientAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clientAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clientAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string usersDT(string symbol) {
            return base.Channel.usersDT(symbol);
        }
        
        public System.Threading.Tasks.Task<string> usersDTAsync(string symbol) {
            return base.Channel.usersDTAsync(symbol);
        }
        
        public string UsersDateSearch(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.UsersDateSearch(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<string> UsersDateSearchAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.UsersDateSearchAsync(startDate, endDate);
        }
    }
}
